name: Publish Packages

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Required for accessing the repository
      packages: write # Required for publishing to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn install

      - name: Build All Packages
        run: yarn workspaces foreach --include ui run build

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish Packages
        run: yarn workspaces foreach --topological-dev run publish
